### ISSUE TITLE
lesspipe 2.02 misbehaving with text files without a `.txt` extension

### ISSUE THREAD

**Issue by callegar** [wofr06/lesspipe.sh#78] opened 2022-02-20 12:37 UTC
TeX files are fundamentally text files, and may get various extensions such as `.tex`, `.sty` (for packages), `.cls` for classes.
Even if unicode is now popular for `.tex` documents in packages and classes it is frequent not to find characters exceeding the ascii range.
Lesspipe goes a bit nut with them. When I try to visualize a `.cls` that is pure ascii I get something like:
```
ESC[38;5;18m\ESC[39mESC[38;5;18mNESC[39mESC[38;5;18meESC[39mESC[38;5;18meESC[39mESC[38;5;18mdESC[39mESC[38;5;18msESC[39mESC[38;5;18mTESC[39mESC[38;5;18meESC[39mESC[38;5;18mXESC[39mESC[38;5;18mFESC[39mESC[38;5;18moESC[39mESC[38;5;18mrESC[39mESC[38;5;18mmESC[39mESC[38;5;18maESC[39mESC[38;5;18mtESC[39mESC[38;5;130m{ESC[39mESC[38;5;130mLESC[39mESC[38;5;130maESC[39mESC[38;5;130mTESC[39mESC[38;5;130meESC[39mESC[38;5;130mXESC[39mESC[38;5;130m2ESC[39mESC[38;5;130meESC[39mESC[38;5;130m}ESC[39m
ESC[38;5;18m\ESC[39mESC[38;5;18mPESC[39mESC[38;5;18mrESC[39mESC[38;5;18moESC[39mESC[38;5;18mvESC[39mESC[38;5;18miESC[39mESC[38;5;18mdESC[39mESC[38;5;18meESC[39mESC[38;5;18msESC[39mESC[38;5;18mCESC[39mESC[38;5;18mlESC[39mESC[38;5;18maESC[39mESC[38;5;18msESC[39mESC[38;5;18msESC[39mESC[38;5;130m{ESC[39mESC[38;5;130msESC[39mESC[38;5;130mcESC[39mESC[38;5;130m-ESC[39mESC[38;5;130mpESC[39mESC[38;5;130mrESC[39mESC[38;5;130maESC[39mESC[38;5;130mcESC[39mESC[38;5;130mtESC[39mESC[38;5;130miESC[39mESC[38;5;130mcESC[39mESC[38;5;130meESC[39mESC[38;5;130m-ESC[39mESC[38;5;130msESC[39mESC[38;5;130meESC[39mESC[38;5;130msESC[39mESC[38;5;130msESC[39mESC[38;5;130miESC[39mESC[38;5;130moESC[39mESC[38;5;130mnESC[39mESC[38;5;130m}ESC[39mESC[38;5;18m[ESC[39mESC[38;5;241m2020ESC[39mESC[38;5;241m/ESC[39mESC[38;5;241m03ESC[39mESC[38;5;241m/ESC[39mESC[38;5;241m19ESC[39mESC[38;5;250m ESC[39mESC[38;5;18mRESC[39mESC[38;5;241m0.2ESC[39m.ESC[38;5;241m3ESC[39mESC[38;5;18m]ESC[39m
<... on and on in this way...>
```
So I need to remember to place a colon after the file name all the time.

Same happens with shell files ending with `.sh`.

If the file is renamed from `.cls` or `.sh` to `.txt` it displays fine.

**Comment by wofr06** [comment] 2022-02-21 12:02
I cannot reproduce your issue. Could you provide more details (by email)

**Comment by callegar** [comment] 2022-02-21 16:17
Thanks, you pointed me to the right direction with your email. The problem is in the colorizer. Manjaro ships with zsh and with that shell files with an `.sty`, `.cls`, `.tex`, `.sh` files get colorized. Unfortunately, I am used to work on bash and I set that one to be my default shell and in bash you do not get the colorization, but all those weird escape sequences.

Initially I was not expecting this to be due to colorization because I do not have any LESSCOLORIZER env variable set. Yet, I have noticed that manjaro sets some LESS_TERMCAP_xx variables:
```
LESSOPEN=|/usr/bin/lesspipe.sh %s
LESS_TERMCAP_mb=
LESS_TERMCAP_md=
LESS_TERMCAP_me=
LESS_TERMCAP_se=
LESS_TERMCAP_so=
LESS_TERMCAP_ue=
LESS_TERMCAP_us=
LESS=-R
```

**Comment by callegar** [comment] 2022-02-21 16:31
So my triaging is now done. The problem here is that Manjaro has a rather extended zsh config script that sets the `LESS=-R` and the `LESS_TERMCAP_xx` variables, but there is no equivalent for bash. So when you are on bash, `less` does not interpret the color sequences at all.

So the issue is mainly from the Manjaro downstream, IMHO. Still, I wonder if it could be possible for `lesspipe.sh` to check
- if its parent process is `less` with the `-R` option
- if the `LESS` env variable is set to include -R
and avoid the colorization at all if neither condition is satisfied.

**Comment by callegar** [comment] 2022-02-21 16:41
As a matter of fact, I am now realizing that `lesspipe.sh` should do exactly what is suggested above. Manual says:
```
Syntax  highlighting  is activated, if the environment variable LESS exists and contains the option -R or less is called with this op‐
       tion. This guarantees, that escape sequences get converted into colors and do not garble the display
```
So my bug is actually that `lesspipe.sh` does not appear to perform that check correctly, because I get the syntax highlighting even in bash, where ther is no LESS variable nor the -R option is used.

**Comment by callegar** [comment] 2022-02-21 17:05
... and more triaging...

`lesspipe.sh` gets confused in its `analyze_args` function. It does so because my filename contains dashes.
Specifically, my filename is `sc-practice-session.cls`. At some point in the function the variable `lessargs` gets set to `less sc-practice-session.cls`. Then, a `sed` with `'s/-[a-zA-Z]*[rR]/-r/'` makes it a `less sc-ractice-session.cls` and in this a `-r` is detected.

A space before the `-[azA-Z]` can help, but the logic would still break with a file named `sc-ra.cls`.  Probably, a smarter `sed` rule or `getopt` could be used to do the analysis in a more robust way. Note that there can be also corner cases like `less -- -Rout.cls` where `-Rout.cls` is a file.

**Comment by wofr06** [comment] 2022-02-21 19:43
The issue was fixed by changing the sed command as proposed. A test has been added for this (#78) and the previous (#77) issue

**Closed as completed by wofr06** 2022-02-21 19:43 UTC

**Comment by callegar** [comment] 2022-02-21 20:06
Because there are still cases not being handled properly, such as
- `less file-with-r-in-name.cls`
- `less -- -r-starting-filename.cls`
and the issue name ended up as being rather far from the real cause of the issue, I wonder if it could make sense to open a new bug such as *analyze_args function fails on corner cases* specifically aimed at having a list of the corner cases that still need to be more reliably dealt with.

Would that be OK/useful?
